local mdimg = require('markdown-image')

describe("is_local", function()
  it("local", function()
    assert.is_true(mdimg.is_local('foobar'))
  end)
  it("http", function()
    assert.is_false(mdimg.is_local('http://example.com'))
  end)
  it("https", function()
    assert.is_false(mdimg.is_local('https://example.com'))
  end)
end)
