local imgup = require('imgup')

describe("store", function()
  it("local gif", function()
    assert.equals('https://post.kyoh86.dev/image/sample_gif.gif', imgup.store('./spec/sample_gif'))
  end)
  it("local png", function()
    assert.equals('https://post.kyoh86.dev/image/sample_png.png', imgup.store('./spec/sample_png'))
  end)
  it("local jpeg", function()
    assert.equals('https://post.kyoh86.dev/image/sample_jpeg.jpeg', imgup.store('./spec/sample_jpeg'))
  end)
end)
